name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create file
        run: echo "Hello from Workflow 1" > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-file
          path: output.txt
