name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]   # Name of first workflow
    types:
      - completed

jobs:
  download-and-use:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: output-file
          path: ./artifact

      - name: Show contents
        run: cat ./artifact/output.txt
